---
kind: "operation"
client: "atomist 1.2"
generator:
  name: "NewRugProject"
  group: "atomist-rugs"
  artifact: "rug-project"
  version: "0.2.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-project.git"
    branch: "27ac2e52f8fa870ac2452944be9f707734218354"
    sha: "27ac2e5"
  parameters:
    - "project_name": "cd-rug-04"
    - "owner": "atomisthqa"
    - "description": "This is my first editor"
    - "version": "0.1.0"

---
kind: "operation"
client: "atomist"
editor:
  name: "AddTypeScript"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.13.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "8f7b8da48226325ba1e7f83520bc7436f9f0f792"
    sha: "8f7b8da"

